sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^3.8.6
  - npm install react react-dom animejs
before_script:
  - npm prune
script:
  - npm run test
  - npm run build:publish
after_success:
- npm run coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
