language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_install:
  - npm i -g npm@^3.8.6
before_script:
  - npm prune
script:
  - npm run test
  - npm run build:publish
after_success:
  - npm run coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
